/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gripgym;

import Controlador.ConexionJDBC;
import Modelo.*;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vero
 */
public class RegistrarFichaMedica extends javax.swing.JFrame {

    private ResultSet rs;
    String sexo="";
    /**
     * Creates new form RegistrarFichaMedica
     */
    public RegistrarFichaMedica() {
        initComponents();
        
        setLocationRelativeTo(null); //Centralizamos la ventana.
        this.setTitle("FICHA MEDICA");
        
         //Color JFrame
        this.getContentPane().setBackground(new java.awt.Color(102,102,102));
        //Color JPanel
        jPanel1.setBackground(new java.awt.Color(102,102,102));
        
        ConexionJDBC.getInstance().AbrirConexion();
        CargarTabla();
        
    }
    
     public void LimpiarCampos() 
     {
         this.txtApeNom.setText("");
         this.txtEdad.setText("");
         this.buttonGroup1.clearSelection();
         this.txtDni.setText("");
         this.txtTel.setText("");
         this.txtCel.setText("");
         this.txtNroFichaMedica.setText("");
         this.txtTelEmergencia.setText("");
         this.txtGrupoSanguineo.setText("");
         this.txtMutual.setText("");
         this.txtEnfermedad.setText("");
         this.txtObservacion.setText("");
     }
    
    private void DeshabilitarCampos()
    {
         this.txtApeNom.setEnabled(false);
         this.txtEdad.setEnabled(false);
         this.rbtFem.setEnabled(false);
         this.rbtMas.setEnabled(false);
         this.txtDni.setEnabled(false);
         this.txtTel.setEnabled(false);
         this.txtCel.setEnabled(false);
         this.btnBuscarFM.setEnabled(false);
    }
     
    
     private void HabilitarCampos()
    {
         this.txtApeNom.setEnabled(true);
         this.txtEdad.setEnabled(true);
         this.rbtFem.setEnabled(true);
         this.rbtMas.setEnabled(true);
         this.txtDni.setEnabled(true);
         this.txtTel.setEnabled(true);
         this.txtCel.setEnabled(true);
         this.btnBuscarFM.setEnabled(true);
         
    }
    
     
     private void DeshabilitarBotones()
     {
         this.btnGuardar.setEnabled(false);
         this.btnEditar.setEnabled(false);
         this.btnCancelar.setEnabled(false);
         this.btnEliminar.setEnabled(false);
     }
     
      private void HabilitarBotones()
     {
         this.btnGuardar.setEnabled(true);
         this.btnEditar.setEnabled(true);
         this.btnCancelar.setEnabled(true);
         this.btnEliminar.setEnabled(true);
     }
    
    
    
         private void CargarTabla() {

        DefaultTableModel tabla = new DefaultTableModel();
        try {
            tabla.addColumn("Nro Ficha");
            tabla.addColumn("D.N.I");
            tabla.addColumn("Cliente");
            tabla.addColumn("Edad");
            tabla.addColumn("Sexo");
            tabla.addColumn("Telefono");
            tabla.addColumn("Celular");
            tabla.addColumn("Tel Emergencia");
            tabla.addColumn("Grupo Sanguíneo");
            tabla.addColumn("Mutual");
            tabla.addColumn("Enfermedad");
            tabla.addColumn("Observación");

            ResultSet rs = ConexionJDBC.getInstance().getCargarTablaFichaMedica();

            while (rs.next()) {
                Object dato[] = new Object[12];
                for (int i = 0; i < 12; i++) {
                    dato[i] = rs.getString(i + 1);

                }
                tabla.addRow(dato);
            }
            this.TablaFichaMedica.setModel(tabla);

        } catch (Exception e) {
        }
    }
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        btnBuscarFM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtApeNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbtFem = new javax.swing.JRadioButton();
        rbtMas = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        lblGrupoSanguineo = new javax.swing.JLabel();
        lblTelEmergencia = new javax.swing.JLabel();
        txtTelEmergencia = new javax.swing.JTextField();
        txtGrupoSanguineo = new javax.swing.JTextField();
        lblMutual = new javax.swing.JLabel();
        txtMutual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNroFichaMedica = new javax.swing.JTextField();
        lblObservacion = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEnfermedad = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFichaMedica = new javax.swing.JTable();
        btnImpirmir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lblIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCliente.setText("D.N.I:");

        btnBuscarFM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar2.png"))); // NOI18N
        btnBuscarFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFMActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");

        buttonGroup1.add(rbtFem);
        rbtFem.setForeground(new java.awt.Color(255, 255, 255));
        rbtFem.setText("Femenino");

        buttonGroup1.add(rbtMas);
        rbtMas.setForeground(new java.awt.Color(255, 255, 255));
        rbtMas.setText("Masculiino");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teléfono:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Celular:");

        lblGrupoSanguineo.setForeground(new java.awt.Color(255, 255, 255));
        lblGrupoSanguineo.setText("Grupo Sanguíneo:");

        lblTelEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        lblTelEmergencia.setText("Tel Emergencia:");

        lblMutual.setForeground(new java.awt.Color(255, 255, 255));
        lblMutual.setText("Mutual:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nro Ficha Médica:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(lblTelEmergencia))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrupoSanguineo)
                            .addComponent(lblIdCliente)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(btnBuscarFM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtFem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtMas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMutual)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMutual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNroFichaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNroFichaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarFM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(rbtFem))
                    .addComponent(rbtMas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelEmergencia)
                    .addComponent(txtTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupoSanguineo)
                    .addComponent(txtGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMutual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMutual))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblObservacion.setForeground(new java.awt.Color(255, 255, 255));
        lblObservacion.setText("Observación:");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout-24.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/New-24.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar-24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar-24.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar3-24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-24.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtEnfermedad.setColumns(20);
        txtEnfermedad.setRows(5);
        jScrollPane2.setViewportView(txtEnfermedad);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Enfermedades:");

        TablaFichaMedica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFichaMedica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFichaMedicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFichaMedica);

        btnImpirmir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printer1(24x24).png"))); // NOI18N
        btnImpirmir.setText("Imprimir");
        btnImpirmir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpirmirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObservacion)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtObservacion)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(27, 27, 27)
                                .addComponent(btnGuardar)
                                .addGap(27, 27, 27)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(32, 32, 32)
                                .addComponent(btnEliminar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImpirmir)
                        .addGap(56, 56, 56)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacion)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnGuardar)
                            .addComponent(btnEditar)
                            .addComponent(btnCancelar)))
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnImpirmir))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFMActionPerformed
        
         //Buscamos el Cliente por DNI y automáticamente carga todos los campos.
        int dni=Integer.parseInt(this.txtDni.getText());
        
         try
        {   ConexionJDBC.getInstance().AbrirConexion();
            rs=ConexionJDBC.getInstance().getCargarClienteFichaMedica(dni);
            if(rs.next())
            {  
                this.txtApeNom.setText(rs.getString(2));
                this.txtEdad.setText(rs.getString(3));
//              -------------------------------------------------
                sexo=rs.getString(4);
                
                if("Femenino".equals(sexo))
                  {this.rbtFem.setSelected(true);}
                else 
                  {this.rbtMas.setSelected(true);} 
//              -------------------------------------------------  
 
                 this.txtTel.setText(rs.getString(5));
                 this.txtCel.setText(rs.getString(6));
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "¡Este cliente no existe!");
                rs.close();
            }
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());}
        
    }//GEN-LAST:event_btnBuscarFMActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.LimpiarCampos();
        this.HabilitarCampos();
        this.HabilitarBotones();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cancelar?", "Cancelar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) 
        {
            this.LimpiarCampos();
            this.DeshabilitarCampos();
            this.DeshabilitarBotones();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        int nroFM=Integer.parseInt(this.txtNroFichaMedica.getText());
        int telEm=Integer.parseInt(this.txtTelEmergencia.getText());
        String grupoS=this.txtGrupoSanguineo.getText();
        String mutual=this.txtMutual.getText();
        String enf=this.txtEnfermedad.getText();
        String obs=this.txtObservacion.getText();
        
        FichaMedica FichaMedica=new FichaMedica(nroFM,grupoS,telEm,mutual,enf,obs);
        ConexionJDBC.getInstance().InsertarFichaMedica(FichaMedica);
        
        this.CargarTabla();
        this.LimpiarCampos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
        int nroFM=Integer.parseInt(this.txtNroFichaMedica.getText());
        int telEm=Integer.parseInt(this.txtTelEmergencia.getText());
        String grupoS=this.txtGrupoSanguineo.getText();
        String mutual=this.txtMutual.getText();
        String enf=this.txtEnfermedad.getText();
        String obs=this.txtObservacion.getText();
        
        FichaMedica FichaMedica=new FichaMedica(nroFM,grupoS,telEm,mutual,enf,obs);
        ConexionJDBC.getInstance().EditarFichaMedica(FichaMedica);
        
        this.CargarTabla();
        this.LimpiarCampos();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void TablaFichaMedicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFichaMedicaMouseClicked
        
                for (int i = 0; i < this.TablaFichaMedica.getRowCount(); i++) 
            {
                String idfm="", dni="", nomape="", edad="", sexo="", tel="", cel="", telem="", grupos="", mutual="", enf="", obs="";
               
               
                idfm = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 0);
                dni = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 1);
                nomape = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 2);
                edad = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 3);
                sexo = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 4);
                tel = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 5);
                cel = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 6);
                telem = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 7);
                grupos = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 8);
                mutual = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 9);
                enf = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 10);
                obs = (String) this.TablaFichaMedica.getValueAt(this.TablaFichaMedica.getSelectedRow(), 11);
                
                this.txtNroFichaMedica.setText(idfm);
                this.txtDni.setText(dni);
                this.txtApeNom.setText(nomape);
                this.txtEdad.setText(edad);
               
//              -------------------------------------------------
                //Condición que evalúa la variable género.
                if("Femenino".equals(sexo))
                {this.rbtFem.setSelected(true);}
                else
                {this.rbtMas.setSelected(true);}
//              -------------------------------------------------
                
                this.txtTel.setText(tel);
                this.txtCel.setText(cel);
                this.txtTelEmergencia.setText(telem);
                this.txtGrupoSanguineo.setText(grupos);
                this.txtMutual.setText(mutual);
                this.txtEnfermedad.setText(enf);
                this.txtObservacion.setText(obs);

            }
        
    }//GEN-LAST:event_TablaFichaMedicaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        //Elimina la fila seleccionada.   
        DefaultTableModel model = (DefaultTableModel) this.TablaFichaMedica.getModel();

        int fila = this.TablaFichaMedica.getSelectedRow();

        if (fila < 0) 
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } 
        else 
        {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea Eliminar el registro? ");

            if (JOptionPane.OK_OPTION == confirmar) 
            {
                int NroFM=Integer.parseInt(this.txtNroFichaMedica.getText());
                ConexionJDBC.getInstance().EliminarFichaMedica(NroFM);
                model.removeRow(fila);
                JOptionPane.showMessageDialog(null, "¡Registro Eliminado!");
            }
        }
        this.CargarTabla();
        this.LimpiarCampos();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImpirmirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpirmirActionPerformed
      ConexionJDBC.getInstance().AbrirConexion();
      ConexionJDBC.getInstance().GenerarReporteFichaMedicaMenu(Integer.parseInt(txtDni.getText()));
    }//GEN-LAST:event_btnImpirmirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarFichaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFichaMedica;
    private javax.swing.JButton btnBuscarFM;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImpirmir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGrupoSanguineo;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblMutual;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblTelEmergencia;
    private javax.swing.JRadioButton rbtFem;
    private javax.swing.JRadioButton rbtMas;
    private javax.swing.JTextField txtApeNom;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextArea txtEnfermedad;
    private javax.swing.JTextField txtGrupoSanguineo;
    private javax.swing.JTextField txtMutual;
    private javax.swing.JTextField txtNroFichaMedica;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTelEmergencia;
    // End of variables declaration//GEN-END:variables
}
