/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gripgym;

import Controlador.ConexionJDBC;
import Modelo.*;
import static gripgym.ParaGenerarPagoCuota.txtDniCliente;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vero
 */
public class RegistrarPagoCuota extends javax.swing.JFrame {

    ResultSet rs;

    /**
     * Creates new form RegistrarPagoCuota
     */
    public RegistrarPagoCuota() {
        initComponents();
        
        setLocationRelativeTo(null); //Centralizamos la ventana.
        this.setTitle("REGISTRAR PAGO CUOTA");
        
        //Color JFrame
        this.getContentPane().setBackground(new java.awt.Color(102,102,102));

         //Insertamos FECHA del Sistema.
        Calendar cal=Calendar.getInstance();
        String fecha=cal.get(cal.DATE)+" / "+(cal.get(cal.MONTH)+1)+" / " +cal.get(cal.YEAR);
        this.lblFechaActual.setText(fecha);
        
        ConexionJDBC.getInstance().AbrirConexion();
        CargarNroPagoCuota();

    }

    
    
    public void CargarNroPagoCuota()
    {String c="";
        try
        {
            ConexionJDBC.getInstance().AbrirConexion();
            rs=ConexionJDBC.getInstance().getCargarNroPagoCuota();
            rs.next();
//            this.txtNroPC.setText(rs.getString(1));
            c=rs.getString(1);
            if(c==null)
                {this.txtNroPC.setText("00000001");}
            else
            {
                int j=Integer.parseInt(c);
                GenerarNumero gen= new GenerarNumero();
                gen.generar(j);
                this.txtNroPC.setText(gen.serie());
            }
        }
        catch(Exception e){}
    }
    
    
    
    
    private void CargarTabla() {

        DefaultTableModel tabla = new DefaultTableModel();
        try {
            tabla.addColumn("Nro Pago Cuota");
            tabla.addColumn("Descripción");
            tabla.addColumn("Importe");
            int nroPC=Integer.parseInt(this.txtNroPC.getText());
            ResultSet rs = ConexionJDBC.getInstance().getCargarDetallePagoCuota(nroPC);

            while (rs.next()) {
                Object dato[] = new Object[3];
                for (int i = 0; i < 3; i++) {
                    dato[i] = rs.getString(i + 1);

                }
                tabla.addRow(dato);
            }
            this.TablaPagoCuota.setModel(tabla);

        } catch (Exception e) {
        }
    }
    
     public void LimpiarCampos() 
     {
         this.txtNroPC.setText("");
         this.txtDni.setText("");
         this.txtApeNom.setText("");
         this.txtFechaI.setCalendar(null);
         this.txtFechaV.setCalendar(null);
         this.txtObservacion.setText("");
         this.txtImporte.setText("");
         this.txtEstado.setText("");
         this.lblImporte.setText("");
         this.LimpiarTabla(this.TablaPagoCuota);
     }
    
    
     
     
public void LimpiarTabla(JTable tabla){

        try {

            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();

            int filas=tabla.getRowCount();

            for (int i = 0;filas>i; i++) {

                modelo.removeRow(0);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");

        }

    }
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNroPC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaI = new com.toedter.calendar.JDateChooser();
        txtFechaV = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPagoCuota = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApeNom = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();
        lblimp = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAGO CUOTA");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nro Pago Cuota:");

        txtNroPC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Inicial:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Vencimiento:");

        TablaPagoCuota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nro Pago Cuota", "Descripción", "Importe"
            }
        ));
        jScrollPane1.setViewportView(TablaPagoCuota);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IMPORTE:");

        lblImporte.setForeground(new java.awt.Color(255, 255, 255));
        lblImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporte.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout-24.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Observación:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha:");

        lblFechaActual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaActual.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaActual.setText("00/00/00");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("D.N.I:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");

        btnBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar2.png"))); // NOI18N
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        lblimp.setForeground(new java.awt.Color(255, 255, 255));
        lblimp.setText("Importe:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar-24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printer1(24x24).png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/New-24.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete(24x24).png"))); // NOI18N
        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBorrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-24.png"))); // NOI18N
        btnBorrarTodo.setText("Borrar Todo");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(197, 197, 197)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNroPC, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnNuevo)
                                                .addGap(32, 32, 32)
                                                .addComponent(btnGuardar)
                                                .addGap(31, 31, 31))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblimp)
                                                            .addComponent(jLabel6))
                                                        .addGap(36, 36, 36)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEliminar)
                                                .addGap(34, 34, 34)
                                                .addComponent(btnBorrarTodo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnBuscarC))
                                            .addComponent(txtApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 272, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 562, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnImprimir)
                                .addGap(157, 157, 157)
                                .addComponent(btnCerrar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNroPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblFechaActual))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarC)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimp)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnNuevo)
                        .addComponent(btnEliminar))
                    .addComponent(btnBorrarTodo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimir)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed

        //Buscamos el Cliente por DNI y automáticamente carga todos los campos.
        int dni=Integer.parseInt(this.txtDni.getText());
        
         try
        {   ConexionJDBC.getInstance().AbrirConexion();
            rs=ConexionJDBC.getInstance().getCargarClientePagoCuota(dni);
            if(rs.next())
            {  
                this.txtApeNom.setText(rs.getString(2));
//                this.txtFechaI.setDate(rs.getDate(3));
//                this.txtFechaV.setDate(rs.getDate(4));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "¡Este cliente no existe!");
                rs.close();
            }
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());}


         
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        int dni=Integer.parseInt(this.txtDni.getText());
        String apenom=this.txtApeNom.getText();
        int nroPagoC=Integer.parseInt(this.txtNroPC.getText());
        Date fechaD=this.txtFechaI.getDate();
        Date fechaH=this.txtFechaV.getDate(); 
        String obs=this.txtObservacion.getText();
        int imp=Integer.parseInt(this.txtImporte.getText());
        String estado=this.txtEstado.getText();
        
        PagoCuota PagoCuota=new PagoCuota(fechaD,fechaH,imp,obs,estado);
        ConexionJDBC.getInstance().InsertarPagoCuota(PagoCuota, dni);
        
        DetallePagoCuota DetallePagoCuota=new DetallePagoCuota(nroPagoC,obs,imp);
        ConexionJDBC.getInstance().InsertarDetallePagoCuota(DetallePagoCuota);
        
//        JOptionPane.showMessageDialog(this, "¡Guardado con éxito!");
        this.CargarTabla();
//        this.LimpiarCampos();
       
    //--------------------------------------------------------------------------    
       
        //Método para sumar los importe.
        double total=0.0;
       
        for(int i=0;i<this.TablaPagoCuota.getRowCount();i++)
        {
            String importeTotal= this.TablaPagoCuota.getValueAt(i, 2).toString();
          
            double impT=Double.parseDouble(importeTotal);
            total+=impT;
             this.lblImporte.setText(""+total);             
         }
    //--------------------------------------------------------------------------  
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        LimpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       ConexionJDBC.getInstance().AbrirConexion();
       ConexionJDBC.getInstance().GenerarReportePagoCuotaMenu(Integer.parseInt(txtDni.getText()));
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed

      
//        Date fechaI=this.txtFechaI.getDate();
//        Date fechaV=this.txtFechaV.getDate(); 
        
//        String fechaI=this.txtFechaI.getCalendar().toString();
//        String fechaV=this.txtFechaV.getCalendar().toString();
//        
//         try
//        {   ConexionJDBC.getInstance().AbrirConexion();
//            rs=ConexionJDBC.getInstance().getEstadoCliente(fechaI, fechaV);
//            if(rs.next())
//            {
//                this.txtEstado.setText(rs.getString(8));
//                this.txtEstado.setBackground(new java.awt.Color(0,153,0));
//            }
//            else
//            {
////                JOptionPane.showMessageDialog(this, "¡Este profesor no existe!");
//                rs.close();
//            }
//        }
//        catch(Exception e)
//        { JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());}
      
        
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
               //Elimina la fila seleccionada.   
        DefaultTableModel model = (DefaultTableModel) this.TablaPagoCuota.getModel();

        int fila = this.TablaPagoCuota.getSelectedRow();

        if (fila < 0) 
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } 
        else 
        {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea Eliminar el registro? ");

            if (JOptionPane.OK_OPTION == confirmar) 
            {
                int nroPC=Integer.parseInt(this.txtNroPC.getText());
                String des=this.txtObservacion.getText();
                double imp=Double.parseDouble(this.txtImporte.getText());
                ConexionJDBC.getInstance().EliminarDetallePagoCuota(nroPC,des,imp);
             
                model.removeRow(fila);
            }
        }
        this.CargarTabla();
        this.lblImporte.setText("");
        
               
    //--------------------------------------------------------------------------    
       
        //Método para sumar los importe.
        double total=0.0;
       
        for(int i=0;i<this.TablaPagoCuota.getRowCount();i++)
        {
            String importeTotal= this.TablaPagoCuota.getValueAt(i, 2).toString();
          
            double impT=Double.parseDouble(importeTotal);
            total+=impT;
             this.lblImporte.setText(""+total);             
         }
    //--------------------------------------------------------------------------  
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        
        int nroPC=Integer.parseInt(this.txtNroPC.getText());
        ConexionJDBC.getInstance().EliminarDetallePagoCuota(nroPC);
        this.CargarTabla();
        this.lblImporte.setText("");
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPagoCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPagoCuota;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblimp;
    public javax.swing.JTextField txtApeNom;
    public javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEstado;
    private com.toedter.calendar.JDateChooser txtFechaI;
    private com.toedter.calendar.JDateChooser txtFechaV;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNroPC;
    private javax.swing.JTextField txtObservacion;
    // End of variables declaration//GEN-END:variables
}
